query Tasks {
  tasks {
    data {
      id
      attributes {
            description
            title
            checked
            creator {
              data {
              attributes {
                username
              }
            }
        }
      }
    }
  }
}   